[[main]]
  name = "Discord"
  identifier = "discord"
  url = "https://discord.gg/ggKddZjrP3"
  weight = 40
  pre = '<i class="fab fa-discord"></i> '
[[main]]
  name = "Plan"
  identifier = "plan"
  url = "http://play.merlecraft.ga:3677/"
  weight = 50
  pre = '<i class="fas fa-link"></i> '
